# Generated by Django 5.2.3 on 2025-07-02 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 2, 13, 52, 55, 110645)),
        ),
    ]
